// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-svphJichvbG2danfH0J3DGxv9HMwHk0',
    appId: '1:231694011080:web:a90ce5b306b171429af3fd',
    messagingSenderId: '231694011080',
    projectId: 'landingpage-ba7ba',
    authDomain: 'landingpage-ba7ba.firebaseapp.com',
    storageBucket: 'landingpage-ba7ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcZY4L3K74Meiaa0z9NcNCoSQuXRM0oZA',
    appId: '1:231694011080:android:39dd04439ab526cb9af3fd',
    messagingSenderId: '231694011080',
    projectId: 'landingpage-ba7ba',
    storageBucket: 'landingpage-ba7ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqmvoYhV6epFNy9hpa95Ye8jjIegrdeTg',
    appId: '1:231694011080:ios:6fd61f8251f254a39af3fd',
    messagingSenderId: '231694011080',
    projectId: 'landingpage-ba7ba',
    storageBucket: 'landingpage-ba7ba.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );
}
